# Thanks to Simon Willison for the inspiration: https://simonwillison.net/2020/Oct/9/git-scraping/
name: Fetch latest train status

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 0/4 * * *' # every four hours https://crontab.guru/#30_0/4_*_*_* TODO: consider less frequent

jobs:
  update-ati-summaries:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Pull Node packages
      run: npm install
    - name: Fetch latest status and convert to CSV
      run: . fetch-and-convert-latest-train-status.sh
    - name: Commit and push if changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add statuses/
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
